# Generated by Django 3.1.2 on 2020-11-19 19:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ARTICLE TITLE', max_length=100)),
                ('author', models.CharField(default='ARTICLE AUTHOR', max_length=40)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date of Publishing')),
                ('content', models.TextField(default='ARTICLE TEXT CONTENTT')),
                ('image_url', models.CharField(default='IMAGE PLACEHOLDER', max_length=100)),
                ('image_caption', models.CharField(default='IMAGE CAPTION', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.article')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Commented On')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.article')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.comments')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='main.articlecategory'),
        ),
    ]
