# Generated by Django 3.1.2 on 2020-11-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_categories',
            field=models.CharField(choices=[('SP', 'Sports'), ('PO', 'Politics'), ('BU', 'Business'), ('CU', 'Culture'), ('ST', 'Science & Technology'), ('WN', 'World News')], default='ST', max_length=25),
        ),
    ]
