# Generated by Django 3.1.3 on 2020-11-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201115_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_caption',
            field=models.CharField(default='IMAGE CAPTION', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='sub_title',
            field=models.CharField(default='ARTICLE SUBTITLE', max_length=200),
        ),
    ]
