# Generated by Django 3.1.3 on 2020-11-17 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201117_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_categories',
        ),
    ]
