# Generated by Django 3.1.2 on 2020-11-17 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201117_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='dop',
        ),
        migrations.AddField(
            model_name='article',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date of Publishing'),
        ),
    ]
